name: 'Tests'

on:
  push:
  schedule:
    # each day at 3:40
    - cron: '40 3 * * *'
  workflow_dispatch:

jobs:
  tests:
    name: 'Tests'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.12']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout to workspace
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Print all environment variables
        run: printenv

      - name: Install requirements.txt
        run: |
          python -m pip install -U setuptools
          python -m pip install -U pip
          python -m pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest test -n auto --capture=no
